{
 "title": "IoT Streaming Dashboard",
 "panels": [
  {
   "title": "🌡 Température moyenne",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT event_minute AS time, avg_temperature FROM analytics.agg_iot_metrics ORDER BY event_minute"
    }
   ]
  },
  {
   "title": "🔥 Température max",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT event_minute AS time, max_temperature FROM analytics.agg_iot_metrics ORDER BY event_minute"
    }
   ]
  },
  {
   "title": "🚨 Événements critiques",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 8, "h": 6 },
   "targets": [
    {
     "rawSql": "SELECT sum(critical_events) FROM analytics.agg_iot_metrics"
    }
   ]
  }
 ]
}